// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiProsegur;

#nullable disable

namespace WebApiProsegur.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("WebApiProsegur.Entidades.DetalleOrdenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdOrden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DetalleOrdenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 2,
                            IdItems = 1,
                            IdOrden = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 4,
                            IdItems = 2,
                            IdOrden = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 5,
                            IdItems = 3,
                            IdOrden = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 3,
                            IdItems = 2,
                            IdOrden = 2
                        });
                });

            modelBuilder.Entity("WebApiProsegur.Entidades.ItemsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Cafe Americano",
                            Precio = 16.0,
                            Tiempo = 3
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Cafe Mocca",
                            Precio = 18.0,
                            Tiempo = 4
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cafe con Leche",
                            Precio = 15.0,
                            Tiempo = 5
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Infusión",
                            Precio = 10.0,
                            Tiempo = 3
                        });
                });

            modelBuilder.Entity("WebApiProsegur.Entidades.ItemsMaterialesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DetalleItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdItems = 1,
                            IdMaterial = 1
                        },
                        new
                        {
                            Id = 2,
                            IdItems = 1,
                            IdMaterial = 5
                        },
                        new
                        {
                            Id = 3,
                            IdItems = 2,
                            IdMaterial = 1
                        },
                        new
                        {
                            Id = 4,
                            IdItems = 2,
                            IdMaterial = 2
                        },
                        new
                        {
                            Id = 5,
                            IdItems = 2,
                            IdMaterial = 3
                        },
                        new
                        {
                            Id = 6,
                            IdItems = 2,
                            IdMaterial = 5
                        },
                        new
                        {
                            Id = 7,
                            IdItems = 3,
                            IdMaterial = 1
                        },
                        new
                        {
                            Id = 8,
                            IdItems = 3,
                            IdMaterial = 2
                        },
                        new
                        {
                            Id = 9,
                            IdItems = 3,
                            IdMaterial = 5
                        },
                        new
                        {
                            Id = 10,
                            IdItems = 4,
                            IdMaterial = 4
                        },
                        new
                        {
                            Id = 11,
                            IdItems = 4,
                            IdMaterial = 5
                        });
                });

            modelBuilder.Entity("WebApiProsegur.Entidades.MateriaPrimaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materiales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 15,
                            Nombre = "Cafe expreso"
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 15,
                            Nombre = "Leche"
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 15,
                            Nombre = "Crema batidad"
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 0,
                            Nombre = "Anis"
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 7,
                            Nombre = "Azucar"
                        });
                });

            modelBuilder.Entity("WebApiProsegur.Entidades.OrdenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdTienda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Impuesto")
                        .HasColumnType("REAL");

                    b.Property<double>("SubTotal")
                        .HasColumnType("REAL");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Ordenes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "Susan",
                            Estado = 1,
                            IdTienda = 1,
                            IdUsuario = 2,
                            Impuesto = 18.719999999999999,
                            SubTotal = 104.0,
                            Total = 122.72
                        },
                        new
                        {
                            Id = 2,
                            Cliente = "Daniel",
                            Estado = 1,
                            IdTienda = 1,
                            IdUsuario = 2,
                            Impuesto = 23.219999999999999,
                            SubTotal = 129.0,
                            Total = 152.22
                        });
                });

            modelBuilder.Entity("WebApiProsegur.Entidades.ProvinciaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Impuesto")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Impuesto = 18.0,
                            Nombre = "Lima"
                        },
                        new
                        {
                            Id = 2,
                            Impuesto = 16.0,
                            Nombre = "Lima Norte"
                        });
                });

            modelBuilder.Entity("WebApiProsegur.Entidades.RolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Supervisor"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Empleado"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("WebApiProsegur.Entidades.TiendasEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tiendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdProvincia = 1,
                            Nombre = "Lima Sur"
                        },
                        new
                        {
                            Id = 2,
                            IdProvincia = 1,
                            Nombre = "Lima Norte"
                        },
                        new
                        {
                            Id = 3,
                            IdProvincia = 2,
                            Nombre = "Chimbote"
                        });
                });

            modelBuilder.Entity("WebApiProsegur.Entidades.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
